Add the FNCS_VOLTTRON_Bridge application
VOLTTRON/deprecated-volttron-applications pull request #25
Opened 2017-02-19 18:24 UTC by afisher1

This branch contains the FNCS_VOLTTRON_Bridge application files as well as a README for how to use

2017-05-26 00:35 UTC, craigpnnl requested changes

2017-05-26 00:35 UTC, craig8 commented on pnnl/FncsVolttronBridge/README.rst
> +====================== FNCS VOLTTRON Bridge======================---------- Overview----------FNCS_Volttron_Bridge.py is a standalone VOLTTRON agent. It is meant to run on a system where the VO
hmmm please remove the ^M from the files this looks not so good here.

2017-05-26 16:09 UTC, afisher1 commented
Wow. I guess gedit was set up for dos line endings or something when I wrote this file. It's been fixed. I also added a note about FNCS needing to be compiled with the same version of ZeroMQ that is packaged with VOLTTRON.

2017-05-31 19:31 UTC, craigpnnl approved these changes

2017-05-31 19:31 UTC, merged