Update to ILC logging.
VOLTTRON/deprecated-volttron-applications pull request #53
Opened 2017-10-31 20:34 UTC by rlutes

2017-10-31 20:34 UTC, craig8 commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/VOLTTRON/volttron-applications/pull/53'>Refresh</a>.<a href='#crh-update-none'></a>

2017-10-31 21:39 UTC, craigpnnl requested changes
Looks mostly good.  I added some suggestions, let me know if you disagree with any of them.

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
>          self.update_base_topic = "{}/{}/".format(analysis_prefix_topic, self.agent_id)
It seems like we have multiple ways of joining going on here.  Perhaps it would be good do do the join on "/" for all of them or just use the "{}/{}".format(foo, bar) instead of multiple types of join.  I would highly recommend not using self.update_base_topic+campus+"/" as a thing.  Perhaps introduce a sep (seperator?)

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +            self.demand_args = parse_sympy(demand_formula["operation_args"])
KeyEror will happen if operation_args is not set?  Is this value checked before here in the code?

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        self.power_meter_topic = topics.DEVICES_VALUE(campus=campus,
continue the spacing with point="all" rather than have it on the same line as path.

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +                                                          path="", point="all")
continue the spacing with point="all" rather than have it on the same line as path.

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
>          self.longest_possible_curtail = len(all_devices) * self.curtail_time * 2
What is the hardcoded 2?  A factor?  Should that be a variable?

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        # self.create_curtailment_publish(current_time_str, device_name, meta)
is this commented out code necessary?

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +            _log.debug("Unable to publish device/subdevice curtailment status message.")
Should include the curtailment topic and message in the debug message?  Should this be an error rather than debug?

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
>              _log.debug("Unable to publish application status message.")
Should this be an error condition with details of ilc_topic headers and application message?

2017-10-31 21:39 UTC, craig8 commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        print exception
Print statements shouldn't be present here.  Use log.error(repr(exception) or traceback)

2017-10-31 21:40 UTC, craig8 commented
:shipit:

2017-10-31 21:40 UTC, craig8 commented
:shipit::gun:

2017-10-31 22:49 UTC, rlutes commented
:shipit:

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +                                                          path="", point="all")
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        self.power_meter_topic = topics.DEVICES_VALUE(campus=campus,
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        print exception
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +            self.demand_args = parse_sympy(demand_formula["operation_args"])
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
>              _log.debug("Unable to publish application status message.")
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +            _log.debug("Unable to publish device/subdevice curtailment status message.")
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
>          self.longest_possible_curtail = len(all_devices) * self.curtail_time * 2
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
> +        # self.create_curtailment_publish(current_time_str, device_name, meta)
:+1:<a href='#crh-update-none'></a>

2017-10-31 22:49 UTC, rlutes commented on pnnl/ILCAgent/ilc/ilc_agent.py
>          self.update_base_topic = "{}/{}/".format(analysis_prefix_topic, self.agent_id)
:+1:<a href='#crh-update-complete'></a>

2017-11-01 02:44 UTC, craigpnnl approved these changes

2017-11-01 02:44 UTC, merged