Proactive diagnostic
VOLTTRON/deprecated-volttron-applications pull request #76
Opened 2020-02-13 22:27 UTC by rlutes

Add proactive diagnostic agent.

2020-02-14 19:49 UTC, shwethanidd requested changes
Overall a well documented code :). Few minor comments. I would prefer to add defaults to most of the parameters getting accessed from config or at least add a try-except block around it.

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +        self.actuator = "platform.actuator"
minor: you can set actuator identity in default config and pull it from there

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                            "information is configured!")
"is NOT configured"

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                LOG.debug("Actuator %s "
Can you check the set_point() of actuator. I think the order of input parameters (point_to_set, value) needs to be swapped

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                    try:
What happens when value is None?

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                            priority=8).get(timeout=5)
Can you check the order of input parameters for set_point()

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +        if inconclusive is not None and inconclusive:
Line# 208: Try exception block needed to catch parse errors

2020-02-14 19:49 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +            for operation_arg in operation_args:
What is the point of this loop? Why are you trying to get the same point value 10 times?

2020-02-19 01:44 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                LOG.debug("Actuator %s "
Tested this is correct.

2020-02-19 01:49 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +            for operation_arg in operation_args:
This loop obtains data over a collection interval.  The data is then averaged and analyzed.  There are 10 samples, the for loop 10 and a gevent.sleep after each get_point.  Do you think there is a cleaner way to do this?

2020-02-21 02:00 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                            "information is configured!")
Fixed

2020-02-21 02:01 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +        self.actuator = "platform.actuator"
Fixed

2020-02-21 02:01 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +        if inconclusive is not None and inconclusive:
Added checks to verify that it can be parsed.

2020-02-21 02:03 UTC, rlutes commented on pnnl/ProactiveDiagnosticAgent/proactive_diagnostic/proactive_diagnostic.py
> +                    try:
None means that it will write None to the point, basically it is BACnet device.

2020-03-02 20:47 UTC, shwethanidd approved these changes

2020-03-02 20:47 UTC, shwethanidd commented on pnnl/ProactiveDiagnosticAgent/configs/config
> +    "building": "3820A",
Replace with dummy campus and building name

2020-03-02 20:47 UTC, merged