Economizer Refactor
VOLTTRON/deprecated-volttron-applications pull request #81
Opened 2020-04-22 20:45 UTC by ChristopherKnight

Creating the request to pull the updated economizer refactor into the repository

2020-05-07 17:58 UTC, rlutes commented
In new_data_message the current time needs to be localized.  Although this does not effect the economizer for consistency all times input into the diagnostics should be localized if possible.

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/constants.py
> +
Please add file header

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/EconCorrectlyOff.py
> +Copyright (c) 2017, Battelle Memorial Institute
Change the year to 2020

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/ExcessOutsideAir.py
> +            if (m - (o * desired_oaf + (r * (1.0 - desired_oaf)))) > 0
more meaningful variables will be helpful in understanding what's going on here.

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/InsufficientOutsideAir.py
> +            _log.info(msg)
Remove if unnecessary

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/economizer_agent.py
> +
Needs a file header

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/economizer_agent.py
> +        self.read_config(config_path)
Please add config store support.

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/economizer_agent.py
> +        self.econ_hl_temp = self.read_argument("econ_hl_temp", 65.0)
If you add config store support, default values can be set in default config dictionary

2020-05-13 19:41 UTC, shwethanidd commented on pnnl/EconomizerRCxAgent/economizer/economizer_agent.py
> +
If self.device_type is neither "ahu" nor "rtu" then cool_call is not defined and throw error later

2020-05-13 19:43 UTC, shwethanidd requested changes
The code seems to be pretty good. Major comments are: 
1. Readme describing about the agent and it's usage is missing. This would be beneficial for external users.
2. Econimizer agent needs to support config store.
3. Some of the equation variables have one syllable names (hard to read the code)
4. File headers are missing for some files

2020-07-14 14:30 UTC, shwethanidd approved these changes

2020-07-14 14:31 UTC, merged