Rcx fix
VOLTTRON/deprecated-volttron-applications pull request #89
Opened 2020-11-03 20:28 UTC by rlutes

Allow diagnostics to run if zone reheat data is not present.

2020-11-03 20:39 UTC, craig8 requested changes

2020-11-03 20:39 UTC, craig8 commented on pnnl/AirsideRCxAgent/airside/diagnostics/schedule_reset_aircx.py
> +        if 64.2 not in list(diagnostic_msg.values()):
what is 64.2?  I see a low high normal referenced on line 281 but where does the 64.2 come in?

2020-11-03 20:39 UTC, craig8 commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/EconCorrectlyOn.py
> +    def economizing_check(self, cooling_call, econ_condition, cur_time):
Why is this function name used more than once in the code base?  Should we extract it into a single function/class that can be overridden with a __call__ functionn?

2020-11-03 20:39 UTC, craig8 commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/EconCorrectlyOn.py
> +    def economizer_conditions(self, current_time):
Same question as above

2020-11-03 20:39 UTC, craig8 commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/ExcessOutsideAir.py
> +    def economizer_conditions(self, current_time):
Same Question

2020-11-03 20:39 UTC, craig8 commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/ExcessOutsideAir.py
> +    def economizing_check(self, econ_condition, cur_time):
Same Question

2020-11-04 00:32 UTC, rlutes commented on pnnl/EconomizerRCxAgent/economizer/diagnostics/ExcessOutsideAir.py
> +    def economizing_check(self, econ_condition, cur_time):
Those functions do similar but different checks.

2020-11-05 00:36 UTC, craig8 approved these changes

2020-11-05 00:36 UTC, merged